default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: your_password
  host: localhost

development:
  <<: *default
  database: your_database_name

test:
  <<: *default
  database: your_database_name_test

production:
  <<: *default
  database: your_database_name_production
  username: your_production_username
  password: <%= ENV['DATABASE_PASSWORD'] %>
